theme: jekyll-theme-chirpy
baseurl: ""
url: "https://ahampriyanshu.com"
lang: en
timezone: Asia/Kolkata

title: Priyanshu Tiwari
tagline: Hello and welcome to my blog.

math: true

description: Hello and welcome to my blog. I usually write about programming, finance, and comedy. You can reach me at ahampriyanshu@gmail.com

twitter:
  username: ahampriyanshu

github:
  username: ahampriyanshu

social:
  name: Priyanshu Tiwari
  email: ahampriyanshu@gmail.com
  links:
    - https://twitter.com/ahampriyanshu
    - https://www.linkedin.com/in/ahampriyanshu
    - https://github.com/ahampriyanshu
    - https://www.instagram.com/ahampriyanshu

img_cdn:

avatar: "/assets/avatar.jpg"

toc: true

pwa:
  enabled: false

comments:
  active: utterances

  disqus:
    shortname:

  utterances:
    repo: ahampriyanshu/meta
    issue_term: title

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

google_analytics:
  id: "G-VSNH6EH1RX"

  pv:
    proxy_endpoint: # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path: # the local PV cache data, friendly to visitors from GFW region

paginate: 20

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /blog/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
