baseURL = "https://ahampriyanshu.com/"
languageCode = "en-us"
title = "Priyanshu Tiwari"
theme = "archie"
copyright = "© ahampriyanshu"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 20

[params]
favicon = "https://raw.githubusercontent.com/ahampriyanshu/blog-v2/main/assets/img/favicons/favicon.ico"
og_image = "https://raw.githubusercontent.com/ahampriyanshu//blog-v2/main/assets/avatar.jpg"
# mode = "auto"
mode = "toggle"
useCDN = true
subtitle = "Hello and welcome to my blog"
description = "Hello and welcome to my blog. I usually write about programming, finance, and comedy. You can reach me at ahampriyanshu@gmail.com"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ahampriyanshu"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
