# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "yazi"
license = "MIT"
licenselink = "https://github.com/ahampriyanshu/yazi/blob/main/LICENSE"
description = "Norm has a blog"
homepage = "http://ahampriyanshu.com/"
tags = []
features = []
min_version = "0.115.4"

[author]
  name = "Priyanshu Tiwari"
  homepage = "http://ahampriyanshu.com/"