import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './styles/global.scss';
import { Header } from './components/Header/Header';
import { Sidebar } from './components/Sidebar/Sidebar';

// const inter = Inter({ subsets: ['latin'] });

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Header />
        <div className='sidebar_container'>
          <Sidebar />
          <div className='content_container'>{children}</div>
        </div>
      </body>
    </html>
  );
}
