#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🗑️ Removing temp build files"

rm -r build || 
(
    echo '🔐 Failed to remove the required directory. Please update ownership permissions and then retry!';
    false;
)

echo '🚚 Pushing the changes to remote repository'

git push -u origin ||
(
    echo '😵 Push failed. Please pull or rebase from the origin repository and then try committing again!';
    false;
)
